const SYMBOL_PROXY = Symbol('O876_REACTOR_PROXY')
const SYMBOL_BASE_OBJECT = Symbol('O876_REACTOR_BASE_OBJECT')
const SYMBOL_ANTI_RECURSIVITY_TAG = Symbol('O876_REACTOR_ANTI_RECURSIVITY_TAG')

module.exports = {
  SYMBOL_PROXY,
  SYMBOL_BASE_OBJECT,
  SYMBOL_ANTI_RECURSIVITY_TAG
}
